# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# development:
#   secret_key_base: dac0cd39564e9236db3d4944f6af4ae07fff1323ba7f10076979749dba3544112f134eefdb2c0ee652906c0571ab144123c2c652bcb5bd660c9580568871374a
#   ciclon_pro_db:
#     :host: 10.0.1.12
#     :name: CTRM_CICLON_PRO
#     :username: appMercon
#     :password: mcgdev9312
#   mcgen_db:
#     :host: 10.0.1.12
#     :name: MCGENS
#     :username: appMercon
#     :password: mcgdev9312
#   cxl_endpoint: http://10.0.1.13:8080/RPCRouterServletSession
#   cxl_user_name: cxluser
#   cxl_password: C0mm0dity82#

# development:
#   secret_key_base: dac0cd39564e9236db3d4944f6af4ae07fff1323ba7f10076979749dba3544112f134eefdb2c0ee652906c0571ab144123c2c652bcb5bd660c9580568871374a
#   ciclon_pro_db:
#     :host: 10.10.31.2
#     :name: CTRM_CICLON_PRO
#     :username: appMercon
#     :password: mcgdev9312
#   mcgen_db:
#     :host: 10.10.31.2
#     :name: MCGENS
#     :username: appMercon
#     :password: mcgdev9312
#   cxl_endpoint: http://10.10.31.30:8080/RPCRouterServletSession
#   cxl_user_name: admin
#   cxl_password: admin

development:
  secret_key_base: dac0cd39564e9236db3d4944f6af4ae07fff1323ba7f10076979749dba3544112f134eefdb2c0ee652906c0571ab144123c2c652bcb5bd660c9580568871374a
  ciclon_pro_db:
    :host: 10.53.0.6
    :name: CXL_NICARAGUA
    :username: appMercon
    :password: mcgdev9312
  mcgen_db:
    :host: 10.53.0.6
    :name: MCGENS
    :username: appMercon
    :password: mcgdev9312
  coffeeorigin_db:
    :host: 10.53.0.6
    :name: COFFEE_ORIGIN
    :username: appMercon
    :password: mcgdev9312
  cxl_endpoint: http://cxlni.merconcoffee.com:8080/RPCRouterServletSession
  cxl_user_name: admin
  cxl_password: admin

test:
  secret_key_base: 0e2cddd0fb0321cbff151f0561e0ded6207d923d975f5d5bda627d4a3c314ec47e47257e98933f3f54b60a26d60a47befc4f0b411f29fe61e42ce7b2cd654791
  ciclon_pro_db:
    :host: 10.53.0.6
    :name: CXL_NICARAGUA
    :username: appMercon
    :password: mcgdev9312
  mcgen_db:
    :host: 10.53.0.6
    :name: MCGENS
    :username: appMercon
    :password: mcgdev9312
  coffeeorigin_db:
    :host: 10.53.0.6
    :name: COFFEE_ORIGIN
    :username: appMercon
    :password: mcgdev9312
  cxl_endpoint: http://cxlni.merconcoffee.com:8080/RPCRouterServletSession
  cxl_user_name: admin
  cxl_password: admin

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 04f7d1f51fa0384bce1563aa6106719a1c466eb6f7ecd8c2c441cee862a1bd07655208348afcf873f48277f43b70c63d961c2dbbeeb5fde0df3000ba2faead93
  ciclon_pro_db:
    :host: 10.53.0.6
    :name: CXL_NICARAGUA
    :username: appMercon
    :password: mcgdev9312
  mcgen_db:
    :host: 10.53.0.6
    :name: MCGENS
    :username: appMercon
    :password: mcgdev9312
  coffeeorigin_db:
    :host: 10.53.0.6
    :name: COFFEE_ORIGIN
    :username: appMercon
    :password: mcgdev9312
  cxl_endpoint: http://cxlni.merconcoffee.com:8080/RPCRouterServletSession
  cxl_user_name: admin
  cxl_password: admin
