source 'http://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.1.6'
# Use sqlite3 as the database for Active Record
gem 'tiny_tds', '~> 0.6.2'
gem 'activerecord-sqlserver-adapter', '~> 4.1.0'

group :assets do
  # Use SCSS for stylesheets
  gem 'sass-rails', '~> 4.0.3'
  # Use Uglifier as compressor for JavaScript assets
  gem 'uglifier', '>= 1.3.0'
  # Use CoffeeScript for .js.coffee assets and views
  gem 'coffee-rails', '~> 4.0.0'
end

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
#gem 'jquery-turbolinks'
gem 'sprockets-rails', '~> 2.2.4'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin]

# Use ActiveDirectory
# gem 'activeldap', '~> 4.0.3'
gem 'net-ldap', '~> 0.8.0'

# Group of gems used just for development
#group :development do
#  gem 'guard-rails', '~> 0.7.1'
#  gem 'guard-livereload', '~> 2.4.0', require: false
#  gem 'rack-livereload', '~> 0.3.15'
#end

# Datatables
gem 'jquery-datatables-rails', '~> 3.1.1'

# Pagination for long list of values from database
gem 'will_paginate', '~> 3.0.7'

# SQL Adapter connectivity
gem 'thin', '~> 1.6.3'

# Excel reader
gem 'roo', '~> 1.13.2'

# XML reader
gem 'nokogiri', '~> 1.6.6.2'

# SOAP client
gem 'savon', '~> 2.10.1'

gem 'swf_fu', '~> 2.0.4'
gem 'rb-readline'
